- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      definition: ""
      namespace: default
  - name: Deploy the application
    k8s:
      state: present
      namespace: default
      definition: ""